#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username postgres <<-EOSQL
    ALTER USER postgres WITH PASSWORD '$BG_DB_PASSWORD';
    CREATE USER $BG_DB_USERNAME WITH PASSWORD '$BG_DB_PASSWORD';
    CREATE DATABASE $BG_DB_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $BG_DB_NAME TO $BG_DB_USERNAME;
    ALTER DATABASE $BG_DB_NAME OWNER TO $BG_DB_USERNAME;
EOSQL